#if !canImport(ObjectiveC)
import XCTest

extension SwiftyGPIOTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwiftyGPIOTests = [
        ("testPlaceholder", testPlaceholder),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SwiftyGPIOTests.__allTests__SwiftyGPIOTests),
    ]
}
#endif
